name: build-docker
on: [push]
jobs:
  build-docker-image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: ls
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        # Execute 'tagize' action
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
          
        - name: Build and Push Docker Image
          run: |
            docker build -t ${{ vars.DOCKERHUB_USERNAME }}/tuto-docker:${{steps.tag.outputs.tag}} .
            docker push ${{ vars.DOCKERHUB_USERNAME }}/tuto-docker:${{steps.tag.outputs.tag}}
        - run : docker images
