name: build-docker
on: [push]
jobs:
  build-docker-image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: ls
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Get tag
          id: tag
          uses: devops-actions/action-get-tag@v1.0.3
          with:
            strip_v: true # Optional: Remove 'v' character from version
            default: v0.0.0 # Optional: Default version when tag not found
        
        - name: Use tag
          run: echo ${{steps.tag.outputs.tag}}
          
        - name: Build and Push Docker Image
          run: |
            docker build -t ${{ vars.DOCKERHUB_USERNAME }}/tuto-docker:${{steps.tag.outputs.tag}} .
            docker push ${{ vars.DOCKERHUB_USERNAME }}/tuto-docker:${{steps.tag.outputs.tag}}
        - run : docker images
